# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class CentalineTransactionsItem(scrapy.Item):
    # define the fields for your item here like:
    TransactionID = scrapy.Field()
    IsRelated = scrapy.Field()
    RegDateString = scrapy.Field()
    CblgCode = scrapy.Field()
    CestCode  = scrapy.Field()
    Data_Source = scrapy.Field()
    Memorial = scrapy.Field()
    RegDate = scrapy.Field()
    InsDate = scrapy.Field()
    PostType = scrapy.Field()
    Price = scrapy.Field()
    Rental = scrapy.Field()
    RFT_NArea = scrapy.Field()
    RFT_UPrice = scrapy.Field()
    INT_GArea = scrapy.Field()
    INT_UPrice = scrapy.Field()
    CX = scrapy.Field()
    CY = scrapy.Field()
    c_estate = scrapy.Field()
    c_phase = scrapy.Field() 
    c_property = scrapy.Field()
    scp_c = scrapy.Field()
    scp_mkt = scrapy.Field()
    pc_addr = scrapy.Field()

class CentalineTransactionsDetailItem(scrapy.Item):
    # Transaction
    ID = scrapy.Field()
    Bigestcode = scrapy.Field()
    Cestcode = scrapy.Field()
    Cblgcode = scrapy.Field()
    ThumbnailUrl = scrapy.Field()
    Consider = scrapy.Field()
    Elocation1 = scrapy.Field()
    X_Axis = scrapy.Field()
    Y_Axis = scrapy.Field()
    CX_Axis = scrapy.Field()
    CY_Axis = scrapy.Field()
    Rft_NArea = scrapy.Field()
    Rft_UPrice = scrapy.Field()
    Int_Garea = scrapy.Field()
    Int_Uprice = scrapy.Field()
    Memorial = scrapy.Field()
    Reg_Date = scrapy.Field()
    Ins_Date = scrapy.Field()
    Int_BlgAge = scrapy.Field()
    RegAddr = scrapy.Field()
    Data_Source = scrapy.Field()
    PostType = scrapy.Field()
    NameTC = scrapy.Field()

    #PropertyInfo
    scp_c = scrapy.Field()
    scp_e = scrapy.Field()
    c_estate = scrapy.Field()
    e_estate = scrapy.Field()
    c_phase = scrapy.Field()
    e_phase = scrapy.Field()
    c_property = scrapy.Field()
    e_property = scrapy.Field()
    pc_addr = scrapy.Field()
    pe_addr = scrapy.Field()
    Est_Type = scrapy.Field()

    #HMA
    HMA_type = scrapy.Field()
    code = scrapy.Field()
    est_type = scrapy.Field()
    dbcode = scrapy.Field()
    dbc = scrapy.Field()
    dbe = scrapy.Field()
    bldggpid = scrapy.Field()
    bldggp_c = scrapy.Field()
    bldggp_e = scrapy.Field()
    url = scrapy.Field()
    hma_id = scrapy.Field()
    HMA_Lng = scrapy.Field()
    HMA_Lat = scrapy.Field()
    hma_c = scrapy.Field()
    hma_e = scrapy.Field()