# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class CentalineTransactionsItem(scrapy.Item):
    # define the fields for your item here like:
    TransactionID = scrapy.Field()
    IsRelated = scrapy.Field()
    RegDateString = scrapy.Field()
    CblgCode = scrapy.Field()
    CestCode  = scrapy.Field()
    Data_Source = scrapy.Field()
    Memorial = scrapy.Field()
    RegDate = scrapy.Field()
    InsDate = scrapy.Field()
    PostType = scrapy.Field()
    Price = scrapy.Field()
    Rental = scrapy.Field()
    RFT_NArea = scrapy.Field()
    RFT_UPrice = scrapy.Field()
    INT_GArea = scrapy.Field()
    INT_UPrice = scrapy.Field()
    CX = scrapy.Field()
    CY = scrapy.Field()
    c_estate = scrapy.Field()
    c_phase = scrapy.Field() 
    c_property = scrapy.Field()
    scp_c = scrapy.Field()
    scp_mkt = scrapy.Field()
    pc_addr = scrapy.Field()

class CentalineTransactionsDetailItem(scrapy.Item):
    # Transaction
    ID = scrapy.Field()
    Bigestcode = scrapy.Field()
    Cestcode = scrapy.Field()
    Cblgcode = scrapy.Field()
    ThumbnailUrl = scrapy.Field()
    Consider = scrapy.Field()
    Elocation1 = scrapy.Field()
    X_Axis = scrapy.Field()
    Y_Axis = scrapy.Field()
    CX_Axis = scrapy.Field()
    CY_Axis = scrapy.Field()
    Rft_NArea = scrapy.Field()
    Rft_UPrice = scrapy.Field()
    Int_Garea = scrapy.Field()
    Int_Uprice = scrapy.Field()
    Memorial = scrapy.Field()
    Reg_Date = scrapy.Field()
    Ins_Date = scrapy.Field()
    Int_BlgAge = scrapy.Field()
    RegAddr = scrapy.Field()
    Data_Source = scrapy.Field()
    PostType = scrapy.Field()
    NameTC = scrapy.Field()

    #PropertyInfo
    scp_c = scrapy.Field()
    scp_e = scrapy.Field()
    c_estate = scrapy.Field()
    e_estate = scrapy.Field()
    c_phase = scrapy.Field()
    e_phase = scrapy.Field()
    c_property = scrapy.Field()
    e_property = scrapy.Field()
    pc_addr = scrapy.Field()
    pe_addr = scrapy.Field()
    Est_Type = scrapy.Field()

    #HMA
    HMA_type = scrapy.Field()
    code = scrapy.Field()
    est_type = scrapy.Field()
    dbcode = scrapy.Field()
    dbc = scrapy.Field()
    dbe = scrapy.Field()
    bldggpid = scrapy.Field()
    bldggp_c = scrapy.Field()
    bldggp_e = scrapy.Field()
    url = scrapy.Field()
    hma_id = scrapy.Field()
    HMA_Lng = scrapy.Field()
    HMA_Lat = scrapy.Field()
    hma_c = scrapy.Field()
    hma_e = scrapy.Field()

class CentalineBuildingInfo(scrapy.Item):
    #Building
    intcestcode = scrapy.Field()
    bigest = scrapy.Field()
    bigestcode = scrapy.Field()
    centaest = scrapy.Field()
    cestcode = scrapy.Field()
    centabldg = scrapy.Field()
    cblgcode = scrapy.Field()
    ThumbnailPath = scrapy.Field()
    geo_refno = scrapy.Field()
    bpolycode = scrapy.Field()
    usage = scrapy.Field()
    e_estate = scrapy.Field()
    e_phase = scrapy.Field()
    e_property = scrapy.Field()
    pe_blgnm1 = scrapy.Field()
    pe_blgnm2 = scrapy.Field()
    pe_addr = scrapy.Field()
    c_estate = scrapy.Field()
    c_phase = scrapy.Field()
    c_property = scrapy.Field()
    pc_blgnm1 = scrapy.Field()
    pc_blgnm2 = scrapy.Field()
    pc_sbnm = scrapy.Field()
    pc_addr = scrapy.Field()
    opdate = scrapy.Field()
    blg_age = scrapy.Field()
    unit_cnt = scrapy.Field()
    x_cnt = scrapy.Field()
    y_cnt = scrapy.Field()
    tpu = scrapy.Field()
    centadist = scrapy.Field()
    c_dist = scrapy.Field()
    e_dist = scrapy.Field()
    clu_ccode = scrapy.Field()
    scp_id = scrapy.Field()
    scp_c = scrapy.Field()
    scp_e = scrapy.Field()
    scp_mkt = scrapy.Field()
    scp_cpa = scrapy.Field()
    scp_rica = scrapy.Field()
    pc_street = scrapy.Field()
    pe_street = scrapy.Field()
    pc_stno = scrapy.Field()
    pe_stno = scrapy.Field()
    lux_final = scrapy.Field()
    lpt_x = scrapy.Field()
    lpt_y = scrapy.Field()
    Lng = scrapy.Field()
    Lat = scrapy.Field()
    x_axis = scrapy.Field()
    x_axis2 = scrapy.Field()
    y_axis = scrapy.Field()
    y_axis2 = scrapy.Field()
    ppt_rank = scrapy.Field()
    est_type = scrapy.Field()
    